//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by ewc.rc
//
#define IDD_MYMBOXDLG                   102
#define IDI_ICON                        107
#define IDD_EDITWAVE                    113
#define IDI_ICONFOR                     114
#define IDI_ICONPLAYSTOP                115
#define IDD_COPYFILE                    122
#define IDD_SETTINGDIAG                 135
#define IDI_ICONFOR2                    137
#define IDI_ICONREW2                    138
#define IDD_SEARCH                      141
#define IDI_ICONMARK                    146
#define IDD_EDITFIND                    147
#define IDD_EDITWEDIT                   149
#define IDI_ICONREW                     200
#define IDD_DYNDLG                      203
#define IDD_EQDLG                       204
#define IDD_NORMDLG                     206
#define IDI_ICONMARKNEXT                208
#define IDI_ICONMARKBACK                209
#define IDD_TRACK                       210
#define IDD_INFO                        212
#define IDI_ICONFOR3                    213
#define IDI_ICONREW3                    214
#define IDI_ICONMARKBACK2               215
#define IDI_ICONMARKBACK3               216
#define IDI_ICONMARKNEXT2               217
#define IDI_ICONMARKNEXT3               218
#define IDR_ACCELERATOR                 220
#define IDD_OVERWRITE                   224
#define IDC_BT1                         500
#define IDC_BTCLEAR                     500
#define IDC_BT2                         501
#define IDC_BT3                         502
#define IDC_EDITSEC                     1009
#define IDC_BTZOOMIN                    1018
#define IDC_BTFILEINFO                  1022
#define IDC_BTEDIT                      1023
#define IDC_SBTIME                      1037
#define IDC_BTZOOMOUT                   1062
#define IDC_BTRESET                     1063
#define IDC_BTLOAD                      1064
#define IDC_BTCUTLEFT                   1065
#define IDC_BTCUTRIGHT                  1066
#define IDC_BTJUMP                      1067
#define IDC_BTFORWARD                   1068
#define IDC_BTUNDO                      1069
#define IDC_BTPLAYSTOP                  1070
#define IDC_BTFORWARD2                  1071
#define IDC_BTJUMPNEXT                  1072
#define IDC_BTSETUP                     1073
#define IDC_BTJUMPBACK                  1074
#define IDC_BTSEARCH                    1075
#define IDC_BTSERCHSPLIT                1076
#define IDC_BTTOP                       1076
#define IDC_BTTRACK                     1076
#define IDC_BTFORWARD3                  1077
#define IDC_BTJUMPBACK2                 1078
#define IDC_PROGBAR                     1079
#define IDC_BTJUMPBACK3                 1079
#define IDC_BTJUMPNEXT2                 1080
#define IDC_BTJUMPNEXT3                 1081
#define IDC_SPINSEC                     1082
#define IDC_EDITMIN                     1087
#define IDC_SPINMIN                     1088
#define IDC_EDITHOUR                    1089
#define IDC_SPINHOUR                    1090
#define IDC_CMBPLAY                     1099
#define IDC_SLIDERCOUNT                 1113
#define IDC_SLIDERBOUND                 1114
#define IDC_RADIOTOP                    1115
#define IDC_RADIOMID                    1116
#define IDC_RADIOEND                    1117
#define IDC_BTMALTI                     1126
#define IDC_BTREW                       1136
#define IDC_BTREW2                      1137
#define IDC_BTREW3                      1138
#define IDC_BTSETDYN                    1157
#define IDC_BTSETEQ                     1158
#define IDC_CHKSHIFT                    1222
#define IDC_EDITCOUNT                   1237
#define IDC_EDITBOUND                   1238
#define IDC_SLIDEREQ0                   1238
#define IDC_EDITEQ0                     1239
#define IDC_SLIDEREQ1                   1240
#define IDC_EDITEQ1                     1241
#define IDC_SLIDEREQ2                   1244
#define IDC_SLIDERDYN0                  1244
#define IDC_EDITEQ2                     1245
#define IDC_EDITDYN0                    1245
#define IDC_SLIDEREQ3                   1246
#define IDC_SLIDERDYN1                  1246
#define IDC_BTSTART                     1246
#define IDC_EDITEQ3                     1247
#define IDC_EDITDYN1                    1247
#define IDC_SLIDEREQ4                   1248
#define IDC_SLIDERDYN2                  1248
#define IDC_BTWAVEOUT                   1248
#define IDC_EDITEQ4                     1249
#define IDC_EDITDYN2                    1249
#define IDC_SLIDEREQ5                   1250
#define IDC_BTHELP                      1250
#define IDC_EDITEQ5                     1251
#define IDC_SLIDEREQ6                   1252
#define IDC_EDITEQ6                     1253
#define IDC_SLIDEREQ7                   1254
#define IDC_EDITEQ7                     1255
#define IDC_BTSTARTCUT                  1260
#define IDC_BTSAVESETTING               1261
#define IDC_BTLOADSETTING               1262
#define IDC_BTSPLIT                     1263
#define IDC_RADIOEQ127                  1264
#define IDC_BTSTARTCUTCM                1264
#define IDC_RADIOEQ255                  1265
#define IDC_RADIOEQ511                  1266
#define IDC_BTNORMAL                    1266
#define IDC_RADIOEQ1023                 1267
#define IDC_EDITLEVEL                   1267
#define IDC_SPINLEVEL                   1268
#define IDC_BTOPTVAL                    1270
#define IDC_EDITBASE                    1271
#define IDC_EDITEXT                     1272
#define IDC_EDITTRACK                   1276
#define IDC_SPINTRACK                   1277
#define IDC_BTMOVETRACK                 1278
#define IDC_EDITTRACK2                  1278
#define IDC_SPINTRACK2                  1279
#define IDC_BTSPLITSAVE                 1281
#define IDC_BTSPLITLOAD                 1282
#define IDC_EDITDIR                     1283
#define IDC_BTREFF                      1284
#define IDC_EDITSETTING                 1285
#define IDC_BTCONNECT                   1286
#define IDC_BTRELOAD                    1287
#define IDC_BTCUTLOAD                   1288
#define IDC_BTCUTSAVE                   1289
#define IDC_CHKSHOWCON                  1291
#define IDC_BTSETMP3                    1292
#define IDC_CHKNULL                     1294
#define IDC_ALLYES                      1295
#define IDC_ALLNO                       1296
#define IDC_EDITMSG                     1297
#define IDC_STOP                        1298
#define IDC_CHKAVR                      1300

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        225
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1301
#define _APS_NEXT_SYMED_VALUE           503
#endif
#endif
